language: ruby
rvm: [2.7.1]

before_install:
  - nvm install 12
  - nvm use 12
  - node --version
  - ruby --version

install:
  - yarn --frozen-lockfile
  - bundle --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - yarn build
  - yarn test
  - yarn test:smoke

cache:
  bundler: true
  yarn: true

notifications:
  slack:
    if: branch = master OR branch =~ ^.*slack.*$
    rooms:
      - secure: FN4trzyyUdtZ6DXj4G3A7YnhqkPyqi8jN9BIdA6S6D2eJEH1gPbZUfbqAW87LKckKZ9iYB5KDF5IuELhR3vv1DeHRqm3MKRU91JVBDT7EXbF86Z1J/JMJxNOcoWdCilcgpnm9NCkMAPFC9h6Y3txYhaLWLsnDaWlvehBsJg+Ql4=
    on_success: change
    on_failure: always
