[build]
  command = "yarn build"
  publish = "_site/"

[[redirects]]
  force = true
  from = "/flexbox"
  to = "/css-flexbox"

[[redirects]]
  force = true
  from = "/flowtype"
  to = "/flow"

[[redirects]]
  force = true
  from = "/gpgconf"
  to = "/gnupg"

[[redirects]]
  force = true
  from = "/gpg"
  to = "/gnupg"

[[redirects]]
  force = true
  from = "/gutom"
  to = "/ph-food-delivery"

[[redirects]]
  force = true
  from = "/handlebars-js"
  to = "/handlebars.js"

[[redirects]]
  force = true
  from = "/harvey-js"
  to = "/harvey.js"

[[redirects]]
  force = true
  from = "/immutable-js"
  to = "/immutable.js"

[[redirects]]
  force = true
  from = "/jade"
  to = "/pug"

[[redirects]]
  force = true
  from = "/package"
  to = "/package-json"

[[redirects]]
  force = true
  from = "/package.json"
  to = "/package-json"

[[redirects]]
  force = true
  from = "/phoenix-ecto@1.3"
  to = "/phoenix-ecto"

[[redirects]]
  force = true
  from = "/sh"
  to = "/bash"

[[redirects]]
  force = true
  from = "/commander-js"
  to = "/commander.js"

[[redirects]]
  force = true
  from = "/es2015"
  to = "/es6"

[[redirects]]
  force = true
  from = "/es2016"
  to = "/es6"

[[redirects]]
  force = true
  from = "/es2017"
  to = "/es6"

[[redirects]]
  force = true
  from = "/es2018"
  to = "/es6"

[[redirects]]
  force = true
  from = "/expect.js"
  to = "/expectjs"

[[redirects]]
  force = true
  from = "/factory_girl"
  to = "/factory_bot"

[[redirects]]
  force = true
  from = "/css-animation"
  to = "/css#animation"

[[redirects]]
  force = true
  from = "/css-background"
  to = "/css#background"

[[redirects]]
  force = true
  from = "/css-font"
  to = "/css#fonts"

[[redirects]]
  force = true
  from = "/css-selectors"
  to = "/css#selectors"

[[redirects]]
  force = true
  from = "/brew"
  to = "/homebrew"

[[redirects]]
  force = true
  from = "/date"
  to = "/datetime"

[[redirects]]
  force = true
  from = "/fetch"
  to = "/js-fetch"
