name: Deploy
on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Notes (read me) ðŸ“–"
        run: |
          # About this workflow:
          # This workflow generates GitHub pages, but IT IS NOT USED. It is
          # only generated as an emergency fallback in case Netlify goes down ðŸ˜Š

      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
          cache: yarn

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - name: "Deploy to gh-pages ðŸš€"
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site

      - name: "Deploy to mirror ðŸš€"
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPOSITORY_NAME: rstacruz/devhints-mirror
          BRANCH: gh-pages
          FOLDER: _site

      - name: "Notify Slack ðŸ“¢"
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
